USE [quavio]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Module](
	[Uuid] [uniqueidentifier] NOT NULL,
	[ModuleName] [nvarchar](128) NOT NULL,
	[DisplayName] [nvarchar](128) NOT NULL,
	[UserId] [uniqueidentifier] NOT NULL,
	[ModuleType] [bit] NOT NULL,
 CONSTRAINT [PK_Module_1] PRIMARY KEY CLUSTERED 
(
	[Uuid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_Module] UNIQUE NONCLUSTERED 
(
	[ModuleName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FieldDataType](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_FieldDataType] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Field](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DisplayName] [nvarchar](128) NOT NULL,
	[FieldName] [nvarchar](128) NOT NULL,
	[IsRequired] [bit] NOT NULL,
	[IsReadOnly] [bit] NOT NULL,
	[DataTypeId] [int] NOT NULL,
	[ModuleId] [uniqueidentifier] NOT NULL,
	[ShowInListMode] [bit] NOT NULL,
 CONSTRAINT [PK_ModuleField] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Row](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ModuleId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_ModuleRow] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Cell](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RowId] [int] NOT NULL,
	[FieldId] [int] NOT NULL,
	[Data] [varbinary](max) NULL,
 CONSTRAINT [PK_ModuleRowField] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_ModuleRowField] UNIQUE NONCLUSTERED 
(
	[FieldId] ASC,
	[RowId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Module] ADD  CONSTRAINT [DF_Module_ModuleType]  DEFAULT ((0)) FOR [ModuleType]
GO
ALTER TABLE [dbo].[Field] ADD  CONSTRAINT [DF_Field_IsRequired]  DEFAULT ((1)) FOR [IsRequired]
GO
ALTER TABLE [dbo].[Field] ADD  CONSTRAINT [DF_Field_IsReadOnly]  DEFAULT ((0)) FOR [IsReadOnly]
GO
ALTER TABLE [dbo].[Field] ADD  CONSTRAINT [DF_Field_ShowInListMode]  DEFAULT ((0)) FOR [ShowInListMode]
GO
ALTER TABLE [dbo].[Cell]  WITH CHECK ADD  CONSTRAINT [FK_ModuleRow_Field_Field] FOREIGN KEY([FieldId])
REFERENCES [dbo].[Field] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Cell] CHECK CONSTRAINT [FK_ModuleRow_Field_Field]
GO
ALTER TABLE [dbo].[Cell]  WITH CHECK ADD  CONSTRAINT [FK_ModuleRow_Field_ModuleRow] FOREIGN KEY([RowId])
REFERENCES [dbo].[Row] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Cell] CHECK CONSTRAINT [FK_ModuleRow_Field_ModuleRow]
GO
ALTER TABLE [dbo].[Row]  WITH CHECK ADD  CONSTRAINT [FK_Row_Module] FOREIGN KEY([ModuleId])
REFERENCES [dbo].[Module] ([Uuid])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Row] CHECK CONSTRAINT [FK_Row_Module]
GO
ALTER TABLE [dbo].[Field]  WITH CHECK ADD  CONSTRAINT [FK_Field_Module] FOREIGN KEY([ModuleId])
REFERENCES [dbo].[Module] ([Uuid])
GO
ALTER TABLE [dbo].[Field] CHECK CONSTRAINT [FK_Field_Module]
GO
ALTER TABLE [dbo].[Field]  WITH CHECK ADD  CONSTRAINT [FK_ModuleField_FieldDataType] FOREIGN KEY([DataTypeId])
REFERENCES [dbo].[FieldDataType] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Field] CHECK CONSTRAINT [FK_ModuleField_FieldDataType]
GO
