//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Com.Dover.Web.Areas.CloudTalkModule.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CloudTalkModuleEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CloudTalkModuleEntities object using the connection string found in the 'CloudTalkModuleEntities' section of the application configuration file.
        /// </summary>
        public CloudTalkModuleEntities() : base("name=CloudTalkModuleEntities", "CloudTalkModuleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CloudTalkModuleEntities object.
        /// </summary>
        public CloudTalkModuleEntities(string connectionString) : base(connectionString, "CloudTalkModuleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CloudTalkModuleEntities object.
        /// </summary>
        public CloudTalkModuleEntities(EntityConnection connection) : base(connection, "CloudTalkModuleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StaticModule_CloudTalk> StaticModule_CloudTalk
        {
            get
            {
                if ((_StaticModule_CloudTalk == null))
                {
                    _StaticModule_CloudTalk = base.CreateObjectSet<StaticModule_CloudTalk>("StaticModule_CloudTalk");
                }
                return _StaticModule_CloudTalk;
            }
        }
        private ObjectSet<StaticModule_CloudTalk> _StaticModule_CloudTalk;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StaticModule_CloudTalk EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStaticModule_CloudTalk(StaticModule_CloudTalk staticModule_CloudTalk)
        {
            base.AddObject("StaticModule_CloudTalk", staticModule_CloudTalk);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="doverModel", Name="StaticModule_CloudTalk")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StaticModule_CloudTalk : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StaticModule_CloudTalk object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="accountId">Initial value of the AccountId property.</param>
        /// <param name="cloudTalkId">Initial value of the CloudTalkId property.</param>
        public static StaticModule_CloudTalk CreateStaticModule_CloudTalk(global::System.Int32 id, global::System.Int32 accountId, global::System.Int32 cloudTalkId)
        {
            StaticModule_CloudTalk staticModule_CloudTalk = new StaticModule_CloudTalk();
            staticModule_CloudTalk.Id = id;
            staticModule_CloudTalk.AccountId = accountId;
            staticModule_CloudTalk.CloudTalkId = cloudTalkId;
            return staticModule_CloudTalk;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccountId
        {
            get
            {
                return _AccountId;
            }
            set
            {
                OnAccountIdChanging(value);
                ReportPropertyChanging("AccountId");
                _AccountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountId");
                OnAccountIdChanged();
            }
        }
        private global::System.Int32 _AccountId;
        partial void OnAccountIdChanging(global::System.Int32 value);
        partial void OnAccountIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CloudTalkId
        {
            get
            {
                return _CloudTalkId;
            }
            set
            {
                OnCloudTalkIdChanging(value);
                ReportPropertyChanging("CloudTalkId");
                _CloudTalkId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CloudTalkId");
                OnCloudTalkIdChanged();
            }
        }
        private global::System.Int32 _CloudTalkId;
        partial void OnCloudTalkIdChanging(global::System.Int32 value);
        partial void OnCloudTalkIdChanged();

        #endregion
    
    }

    #endregion
    
}
